name: Doxygen Action
run-name: Build doxygen documentation.

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building doxygen documentation for ${{ github.repository }}/${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: ${{ github.workspace }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
